name: "check-dynamodb"
on:
  push:
    branches:
      - dynamodb
jobs:
  checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          yarn install
          docker compose -f .dynamodb-local-docker/docker-compose.yml up -d
          yarn sls dynamodb migrate
          docker compose -f .dynamodb-local-docker/docker-compose.yml down
        env:
          APP_ENV: dev
          IS_LOCAL: 1
          DYNAMODB_PORT: 8000
