name: "check-dynamodb"
on:
  push:
    branches:
      - dynamodb
jobs:
  checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "17"
      - run: java --version
  
