name: "check-dynamodb"
on:
  push:
    branches:
      - dynamodb
jobs:
  checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - run: |
          java --version
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          yarn install
          yarn sls dynamodb install
          yarn sls dynamodb start
